### ISSUE TITLE
json3 dependency

### ISSUE THREAD

**Issue by thomsbg** [Automattic/socket.io-parser#21]
What is the purpose of this dependency? I am seeking to reduce the size of my asset bundle, and the unminified size of json3 is ~ 39kB. Why not use the standard JSON.stringify / JSON.parse?

**Comment by rase-** [comment]
@defunctzombie yeah that's the reason. 

In general we've tried to keep socket.io and all of its modules as "clean" as possible, not using polyfills. I think it's worth discussing this strategy over again though, imo.

I'll close, and let's chat about this elsewhere.

**Comment by xPaw** [comment]
@rase- What old browsers does socket.io target that do not support JSON? Looking at https://github.com/socketio/socket.io#cross-browser it targets IE9, and JSON is supported in IE8 and up.
